AllCops:
  TargetRubyVersion: 2.6.1
  Exclude:
    - 'bin/**/*'
    - 'test/channels/application_cable/connection_test.rb'
    - 'config/initializers/devise.rb'
    - 'db/**/*'

Documentation:
  Enabled: False
Metrics/ClassLength:
  Max: 150
  CountComments: false
Layout/LineLength:
  Max: 140
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
Metrics/MethodLength:
  Max: 25
  Exclude:
    - "**/*_spec.rb"
Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
