version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.1
    steps:
      - checkout
      - run: echo "A first hello"
  rubocop:
    docker:
      - image: circleci/ruby:2.6.1
    steps:
      - checkout
      - run: gem install bundler
      - run: bundle install
      - run: bundle exec rubocop

workflows:
  version: 2
  build_and_rubocop:
    jobs:
      - build
      - rubocop
